version: '3.8'
services:
  db:
    image: postgres:12-alpine
    container_name: myapp-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - myapp
    ports:
      - '${DB_PORT}:5432'

  redis:
    image: redis:6-alpine
    container_name: myapp-redis
    networks:
      - myapp
    ports:
      - '${REDIS_PORT}:6379'

networks:
  myapp:
    driver: bridge
